### ISSUE TITLE
求指教,不可以保存文件?

### ISSUE THREAD

**Issue by lydlovezjr** [PrototypeZ/SaveState#10]

**Comment by PrototypeZ** [comment]
您好，你指的是不是 File 类型的字段，File 实现了 Serializable 接口，框架支持保存，但是目前的版本做的不好，必须把字段申明为 Serializable 才能自动保存恢复，我正在修改这一版，可以在直接声明 File 的情况下，检测到 File 实现了 Serializable 接口，以 Serializable 的形式进行保存与恢复，非常感谢您的建议，完成以后我会在这里再通知您，再次感谢~

**Comment by PrototypeZ** [comment]
你好，现在已经支持任何实现了 Serializable  接口的类型的自动恢复了，声明实际类型即可，无需声明 Serializable  类型，欢迎使用。

**Comment by PrototypeZ** [comment]
当前版本为 0.2.1 版本
