### ISSUE TITLE
我在fragment使用不生效，activity可以

### ISSUE THREAD

**Issue by protectedMan** [PrototypeZ/SaveState#15]

**Comment by PrototypeZ** [comment]
你好，在 Fragment 恢复的时机是在 onActivityCreated 里，请问不生效是不是指在 onCreateView 回调中不生效，系统执行 onCreateView 的时候有时候无法再这个方法里进行恢复，推荐您把访问状态变量的逻辑 post Runnable 一下，可以确保这些变量被恢复，具体您可以 clone 仓库看一下样例代码，谢谢！
