### ISSUE TITLE
只能存Public变量

### ISSUE THREAD

**Issue by QiLiKing** [PrototypeZ/SaveState#17]
这个插件很好用！不过貌似只能存public的，可否通过反射来保存其他的变量呢？

**Comment by PrototypeZ** [comment]
你好，目前支持非 private 的变量，包括public default protected。目前支持保存的变量类型可以在 README 中查看，谢谢您的支持！

**Comment by QiLiKing** [comment]
好的，谢谢！
  
  
  

  
  
  
  
  
>
