### ISSUE TITLE
为啥在注解处理器里生成saveState工具类，然后再在transfrom里往activity加代码

### ISSUE THREAD

**Issue by huxq17** [PrototypeZ/SaveState#2]
rt,有什么讲究么？

**Comment by BCsl** [comment]
一般来说使用 APT 就完事了，但是还需要开发者在特定的方法调用注解生成的类来注入，使用 transform 就是为了再进一步的简化流程吧

**Comment by PrototypeZ** [comment]
@BCsl 你说得是对的，目前是这种方案，因为我比较熟悉，实现比较快，后续版本可能会考虑只使用 Transform API，现在我只对外只暴露插件这一个接口就是为了以后可能发生的改变做准备的，这样用户可以无感知无缝切换到新的实现 ：）
