### ISSUE TITLE
和注解框架冲突

### ISSUE THREAD

**Issue by jielundewode** [PrototypeZ/SaveState#7]
这个和注解框架（https://github.com/androidannotations）冲突，编译不通过，有解决方案吗
`@FragmentArg
    @JvmField
    @AutoRestore
    var type = 0//（1表示标准课程，0 表示学习历史）}`

**Comment by PrototypeZ** [comment]
请问：
1. 遇到的报错信息是什么？
2. 项目中有无启用kotlin？
3. 是否使用本项目的最新版本？
4. 您使用的Gradle版本是多少？
5. 您的 Gradle 文件配置片段可否贴上来？

以上信息能否提供一下，谢谢！

**Comment by jielundewode** [comment]
![qq 20180713153011](https://user-images.githubusercontent.com/10189846/42678928-02c28604-86b3-11e8-9a62-93b11febe14b.png)

**Comment by jielundewode** [comment]
2.使用了kotlin
3.是
4.Gradle版本是4.4
`buildscript {
    ext.kotlin_version = '1.2.51'
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "https://www.jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // dependency for save-state
        classpath "io.github.prototypez:save-state:0.1.6"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}`

> `apply plugin: 'com.android.application'
apply plugin: "kotlin-kapt"

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

apply plugin: 'save.state'`

**Comment by jielundewode** [comment]
`buildscript {
    ext.kotlin_version = '1.2.51'
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "https://www.jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // dependency for save-state
        classpath "io.github.prototypez:save-state:0.1.6"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}`

**Comment by PrototypeZ** [comment]
谢谢您汇报这个问题，原因已经定位到，我会尽快修复

**Comment by PrototypeZ** [comment]
@jielundewode 您好，刚刚 release 0.1.7, 修复了上述问题，您可以再试一下

**Comment by jielundewode** [comment]
谢谢，问题得到解决
