### ISSUE TITLE
When is the data stored ?

### ISSUE THREAD

**Issue by abiemann** [PrototypeZ/SaveState#8]
my implementation below doesn't work. I collect all the data in onPause() but when I leave the app, close it, and relaunch it then the data isn't loaded. When is the data saved ?

    @AutoRestore String autoRestore_dob;
    @AutoRestore Integer autoRestore_state_pos;
    @AutoRestore Integer autoRestore_gender_pos;
    @AutoRestore Boolean autoRestore_tobacco_yes;
    @AutoRestore Boolean autoRestore_tobacco_no;

    @Override
    public void onCreate(Bundle inState) {
        super.onCreate(inState);
        ButterKnife.bind(this);
		// code
        restoreState();
    }
	
    private void restoreState(){
        if (autoRestore_dob != null) dob.setText(autoRestore_dob);
        if (autoRestore_state_pos != null) stateSpinner.setSelection(autoRestore_state_pos);
        if (autoRestore_gender_pos != null) genderSpinner.setSelection(autoRestore_gender_pos);
        if (autoRestore_tobacco_yes != null) radioYes1.setChecked(autoRestore_tobacco_yes);
        if (autoRestore_tobacco_no != null) radioNo1.setChecked(autoRestore_tobacco_no);
    }
	
    @Override
    protected void onPause() {
        saveState();
        super.onPause();
    }

    private void saveState(){
        autoRestore_dob = dob.getText().toString();
        autoRestore_state_pos = stateSpinner.getSelectedItemPosition();
        autoRestore_gender_pos = genderSpinner.getSelectedItemPosition();
        autoRestore_tobacco_yes = radioYes1.isChecked();
        autoRestore_tobacco_no = radioNo1.isChecked();
    }

**Comment by abiemann** [comment]
oh I see now... the library generates the onSaveInstanceState() and onRestoreInstanceState().
Unfortunately, onSaveInstanceState() is unreliable - it's not always triggered, but is typically triggered on phone rotations.
I need it more reliable... I need the data saved whenever onPause() is called.

**Comment by PrototypeZ** [comment]
Thanks for your suggestion! And yes I wrote this lib to help app data survive on orientation change and situation that app is killed by system unexpectedly  when it is brought to background. It isn't a data persistent library by design. But I think your suggestion is interesting, I'm considering to add this functionality to later versions, thanks :)

**Comment by PrototypeZ** [comment]
After consideration, I think SaveState is only a simple tool, and adding data persistent function to it would make it a little complex, so temporary I am not planning to change it. If more guys ask me for this feature then reopening this issue is ok.
